### ISSUE TITLE
Fails to build with glibc 2.38 and `-Werror=format-security`

### ISSUE THREAD

**Issue by Ma27** [brummer10/libxputty#12]
When building mamba 2.5 with libxputty at 62ec1cf and with gcc 12.3 (with `-Werror=format-security`) and glibc 2.38, the build fails like this:

    ../xputty/xfilepicker.c:225:5: error: format not a string literal and no format arguments [-Werror=format-security]
      225 |     asprintf(&filepicker->path, path);
          |     ^~~~~~~~

The full log is available at https://hydra.nixos.org/build/230518081.

I guess this popped up now because `asprintf` and friends is in glibc 2.38 available by default and because of that, the format warning is actually triggered on said function.

Anyways, while it's indeed a workaround to switch to `-Wno-error`, I think it's still reasonable to fix that warning properly in the code.

**Comment by brummer10** [comment]
Hi
Thanks for reporting the error. I've pushed a fix for it to the repository and updated libxputty in mamba to implement the fix there as well. 

regards
hermann
